
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T03:38:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d544102eecb036d084c5f9b2e3235caf0952f0b",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
