
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T15:53:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "46e5ca2d2f8fb2fcb4995acee845bf5716c77cf1",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
