#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['stdlibs', 'stdlibs.tests']

package_data = \
{'': ['*']}

setup(name='stdlibs',
      version='2021.3.30',
      description='List of packages in the stdlib',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://github.com/jreese/stdlibs',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
