
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T15:36:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "61291abf7795b923af8a88c7ff0a9cd496e113c6",
 "version": "2.5.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
