
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T10:56:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4d295d2ce79a5a204c1a46e0b6d813d48e36162",
 "version": "0.7.0.post.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
