
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T08:41:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aaf2c87eba2912c7d3f2c0ac192dbffe8dc11fa0",
 "version": "0.7.0.post.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
