
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T11:02:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6dbc6df5e42f2036d92fa7825b92b0090bf6c42d",
 "version": "1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
