
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T17:20:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c396ec549b76c23960480516d631ef6eb0bcee36",
 "version": "2021.03.post30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
