
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T10:48:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9572bd85696360d9d4711ecf4ac951cb5878eab",
 "version": "0.7.0.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
