
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:23:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cba0ebceb4a721a91e1a66f96d76f3e154b85326",
 "version": "0.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
