version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  graph-insert:
    lang: python3-fastinit
    handler: ./graph-insert
    image: gcr.io/astute-impulse-303109/graph-insert:latest
    build_args:
        REPO_URL: https://gitlab.com/api/v4/projects/23354738/packages/pypi/simple
        SHAVED_URL: gitlab.com/api/v4/projects/23354738/packages/pypi/simple
        REPO_NAME: monorepo_packages
        ACCESS_TOKEN: gtcd2sbMhFUG8zQDrGxU
    
    environment:
      PG_USER: postgres
      PG_PASSWORD: 8HykTNVQDv
      PG_HOST: postgresql.default.svc.cluster.local
      PG_DATABASE: postgres

      ARANOGO_DATABASE: lego_castle
      ARANOGO_USER: starman
      ARANOGO_PASSWORD: 8uLiSAXHM0g7t1Hjoo27
      ARANOGO_HOST: "d997f59f427a.arangodb.cloud"
      ARANOGO_SCHEME: "https"
      RANDOM_GUY: "fun"
configuration:
  templates:
    - name: python3-fastinit
      source: https://gitlab.com/kivo360/python-fastapi-poetry-template