
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T11:11:07+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cd1e58283d4963455dff57183208f16d3dbe589",
 "version": "0.6.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
