name: fasttext-serving # you probably want to 'snapcraft register <name>'
version: '0.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: fastText model serving service # 79 char long summary
description: |
  fastText model serving service
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
parts:
  fasttext-serving:
    plugin: rust
    source: .
apps:
  fasttext-serving:
    command: env PATH=$SNAP/bin:$PATH fasttext-serving
