[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pymacsay"
author = "amkdg"
author-email = "amkdg@protonmail.com"
home-page = "https://github.com/amkdg/pymacsay"
classifiers = [ "License :: OSI Approved :: MIT License",]

