
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T05:40:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a7b671bf84334e968e1e53cbcfc7043ffbcaa69",
 "version": "0.7.0.post.dev40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
