
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-28T12:37:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "372b4d88852e7deae8c5070877c5e92bbf12bfdb",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
