
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T10:04:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e683e594ecd25153a63927b81114d0dfd22e669",
 "version": "1.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
