
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "770e58930a00a9a7351752629f3965af111bf757",
 "version": "1.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
