
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T13:36:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9bed90cdc9c224d9d8b890c2ecf1a69b75027b0",
 "version": "0.0.84.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
