# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/network/socket_interface/v3/default_socket_interface.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class DefaultSocketInterface(betterproto.Message):
    """
    Configuration for default socket interface that relies on OS dependent
    syscall to create sockets.
    """

    pass

    def __post_init__(self) -> None:
        super().__post_init__()
