[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.towncrier]
package = "pynim"
package_dir = "src"
title_format = "{version} ({project_date})"

[tool.vendoring]
destination = "src/pynim/"
requirements = "requirements.txt"
protected-files = ["__init__.py"]