
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T07:48:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1baca5fdfbda3c63fbadd58f09cefc3a95d8718b",
 "version": "0.7.0.post.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
