name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check_skip:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/setup.py') }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: check OS
        run: cat /etc/os-release
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y espeak-ng git
          sudo apt install -y python3-wheel gcc
      - name: Upgrade pip
        # so we can take advantage of pyproject.toml build-dependency support
        run: python3 -m pip install --upgrade pip
      - name: Install TTS
        run: |
          python3 -m pip install .
          python3 setup.py egg_info
      - name: Lint check
        run: |
          cardboardlinter
      - name: Unit tests
        run: nosetests tests --nocapture --processes=0 --process-timeout=20 --process-restartworker
      - name: Test scripts
        run: |
          ./tests/test_demo_server.sh
          ./tests/test_glow-tts_train.sh
          ./tests/test_tacotron_train.sh
          ./tests/test_vocoder_gan_train.sh
          ./tests/test_vocoder_wavegrad_train.sh
          ./tests/test_vocoder_wavernn_train.sh
          ./tests/test_speedy_speech_train.sh
          ./tests/test_resample.sh
          ./tests/test_compute_statistics.sh
