
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "959ff13b05d9cb74ebc103226b3cfa2d1b061e94",
 "version": "0.17.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
