
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T18:13:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "54ce823e736437e5a43779f0967427e0bceb8496",
 "version": "v0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
