[tool.poetry]
name = "xray-node"
version = "0.0.1"
description = ""
authors = ["laoshan-taoist <65347330+laoshan-taoist@users.noreply.github.com>"]
license = "AGPLv3"
packages = [
    { include = "xray_node" },
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.17.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest-asyncio = "^0.14.0"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.poetry.scripts]
xnode = "xray_node.main:main"

[tool.black]
line-length = 120
target-version = ["py38"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
