
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T18:13:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b3a8f18eb10d3a5d952049ed1e7150bdba557cd",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
