
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T16:01:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "56feea50351dd27b92f746942d96b05cde7d8d8a",
 "version": "1.74.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
