
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T23:42:37+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf9624131ddbc6a3de548fb8b68f371227049151",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
