[tool.poetry]
name = "telefast"
version = "0.0.1-pre"
description = ""
authors = ["aahnik <daw@aahnik.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Telethon = "^1.21.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.6"
pytest = "^6.2.2"
pylint = "^2.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
