
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-28T01:50:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8200cbeda72e7428194e174ef083a1d2b33f1f6",
 "version": "0.4.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
