[tool.poetry]
name = "datasett"
version = "0.0.1"
description = ""
authors = ["pbencze <paul@idelab.com>"]
license = "MIT"
packages = [
    { include = "datasett/**/*.py" },
]

[tool.poetry.dependencies]
python "=3.9.2"
dask ="2021.3.1"
gcsfs = "0.7.2"
google-api-core = "1.26.3"
google-auth = "1.28.0"
google-auth-oauthlib ="0.4.4"
google-cloud = "0.34.0"
google-cloud-bigquery = "2.13.1"
google-cloud-core = "1.6.0"
google-cloud-datacatalog = "3.1.1"
google-cloud-datastore = "2.1.0"
numpy = "1.20.2"
pandas = "1.2.3"
pyarrow = "^3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
