##
## Copyright (c) 2021, Empa, Leonie Fierz, Aaron Bojarski, Ricardo Parreira da Silva, Sven Eggimann.
##
## This file is part of CESAR-P - Combined Energy Simulation And Retrofit written in Python
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, either version 3 of the
## License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## Contact: https://www.empa.ch/web/s313
##
EPLUS_ADAPTER:
    EPLUS_VERSION: "9.3.0" # "9.2.0"
    CUSTOM_IDD_8_5: "ressources/Energy+_8-5_NrOfVerticesExtended.idd"
    CUSTOM_IDD_8_7: "ressources/Energy+_8-7-0_NrOfVerticesExtended.idd"
    CUSTOM_IDD_8_8: "ressources/Energy+_8-8-0_NrOfVerticesExtended.idd"
    CUSTOM_IDD_8_9: "ressources/Energy+_8-9-0_NrOfVerticesExtended.idd"
    CUSTOM_IDD_9_1: "ressources/Energy+_9-0-1_NrOfVerticesExtended.idd"
    CUSTOM_IDD_9_2: "ressources/Energy+_9-2-0_NrOfVerticesExtended.idd"
    CUSTOM_IDD_9_3: "ressources/Energy+_9-3-0_NrOfVerticesExtended.idd"
    EPLUS_WINDOWS_DEFAULT_PATH: "C:/EnergyPlusV{version}"
    EPLUS_LINUX_DEFAULT_PATH: "/usr/local/EnergyPlus-{version}"
    EPLUS_MAC_DEFAULT_PATH: "/Applications/EnergyPlus-{version}"
    DO_CREATE_CSV_RESULTS: False # create per building csv results file (same data as in eplusout.eso)
    EPLUS_RUN_VERBOSE: False # if true, some output is sent to console during energy plus run. use this option for debugging.
    SIMULATION_SETTINGS:
        MIN_SYSTEM_TIMESTAMP: 2
        MAX_HVAC_ITERATIONS: 25
        NR_OF_TIMESTEPS: 4
        SHADOW_CALCULATION_FREQUENCY: 7
    OUTPUT_VARS: # for all possible frequencies, see cesar.eplus_adapter.idf_strings.ResultsFrequency
      # if you overwrite in the custom config, you have to specify all parameters you want. the lists are not merged
      HOURLY:
        - "Zone Air Temperature"
        - "Zone Ideal Loads Supply Air Total Heating Energy"
        - "Zone Ideal Loads Supply Air Total Cooling Energy"
        - "Hot Water Equipment District Heating Energy"
        - "Zone Ideal Loads Supply Air Sensible Heating Rate"
        - "Hot Water Equipment District Heating Rate"
    OUTPUT_METER: # for all possible frequencies, see cesar.eplus_adapter.idf_strings.ResultsFrequency
      # if you overwrite in the custom config, you have to specify all parameters you want. the lists are not merged
      ANNUAL:
        - "DistrictHeating:Facility"
        - "DistrictCooling:Facility"
        - "Electricity:Facility"
        - "DistrictHeating:HVAC"
        - "DistrictHeating:Building"
      HOURLY:
        - "DistrictHeating:Facility"
        - "DistrictCooling:Facility"
        - "Electricity:Facility"
        - "DistrictHeating:HVAC"
        - "DistrictHeating:Building"
    EIO_READER:
      ZONE_SUMMARY_START_TAG: "! <Zone Summary>" # zone summary is expected before zone info in the eio file
      IDX_NR_OF_ZONES: 1 # second entry on summary line is the number of zones
      ZONE_INFO_TO_SUMMARY_OFFSET: 0
      FLOOR_AREA_HEADER: "Floor Area {m2}"
      AREA_UNIT: "m**2"
      SEPARATOR: ","

