[config]
enable_webhooks = false
webhook_address = "https://webhooks.com/webhook"
zip_types = [ ".tar.gz", ".bz2", ".zip" ] # Does Nothing Yet 
verbose = false

[vars]
MY_ROOT = "/"

[defaults]
destination = "/backups"
clean_up = false
all_files = true
keep = 1
audit = true
oldest = 4

# [[jobs]]
# name = "Backup"
# source = [
#   "${MY_ROOT}/src/test_data",
# ]


