
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T14:47:20+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cd7bd453ed7b882bbac83c3800ab10c5f608753",
 "version": "0.0.86.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
