name: Pull request unit tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build-pipenv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      pip install linkml-model
      pip install git+https://github.com/hsolbrig/pyld
      run: pipenv install --dev

    - name: Test with unittest
      run: pipenv run python -m unittest discover -p 'test_*.py'
