
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T08:19:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "72075c491fb819c8cfc9b49bd11eb0f379cf5610",
 "version": "0.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
