
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T13:15:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f9f4a6cfb0cccfda8740d64c766ad368c52d78e",
 "version": "6.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
