[tool.poetry]
name = "hasanpy"
version = "0.1.0"
description = "A Python implementation of the Chicken esoteric programming language, with Hasan as its only token"
license = "MIT"
authors = ["kosayoda <mdibaiee@protonmail.com>"]
repository = "https://github.com/mdibaiee/hasanpy"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
hasanpy = "hasanpy.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
