
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:58:14+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e95dcf7b0683b595df50e9aaf0ebef1aeb804bf",
 "version": "2.5.20.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
