DEFAULT_STRINGS = {
    "btn-next-page": "{{page}} »",
    "btn-prev-page": "« {{page}}",
    "btn-pagination": "·{{page}}/{{maxpage}}·",
    "btn-back": "Назад",
    "btn-finish": "Завершить",
    "btn-done": "Готово",
    "btn-close": "Закрыть",
    "btn-save": "Сохранить",
    "btn-editor": "Редактор",
    "btn-skip": "Пропустить",
    "btn-add": "Добавить",
    "btn-create": "Создать",
    "btn-delete": "Удалить",
    "btn-delete-labelled": "Удалить {{label}}",
    "btn-edit-name": "Сменить название",
    "btn-label": "{{label}}",
    "btn-yes": "Да",
    "btn-no": "Нет",
}