
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T06:51:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1de63ce57561274f43ed54ec1b3cf3a3b5a2b001",
 "version": "0.7.0.post.dev42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
