
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T15:32:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7099f87cfa1f6c45083142034b3275f61fe9417",
 "version": "0.8.3b0.dev202104010705"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
