[tool.poetry]
name = "idesyde"
version = "0.1.6"
description = "Generic Design Space Exploration for models based system design"
authors = ["jordao <jordao@kth.se>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
forsyde-io-python = "^0.2"
numpy = "^1.20"
sympy = "^1.7"
minizinc = "^0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
