[tool.poetry]
name = "sayjira"
version = "0.1.0"
description = ""
authors = ["sblokhin <sblokhin@mobiledimension.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.4.1"
wheel = "^0.36.2"
GitPython = "^3.1.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
