#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['log_decorator']

package_data = \
{'': ['*']}

setup(name='log_decorator',
      version='0.1',
      description='A simple execution time logger implemented as a python decorator. Available under the terms of the MIT license.',
      author='Helge Boeschen',
      author_email='helgeboeschen@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
     )
