[tool.poetry]
name = "autodoc_pydantic"
version = "0.1.0"
description = ""
authors = ["mansenfranzen <franz.woellert@gmail.com>"]
packages = [{ include = "sphinxcontrib" }]

[tool.poetry.dependencies]
python = ">=3.6.1"
Sphinx = ">=3.0"
pydantic = ">=1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.0"
sphinx-rtd-theme = "^0.5.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report term --cov-report xml:coverage.xml --cov=sphinxcontrib"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
