
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T16:04:28+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d6e8843c947d690544cecf389256c56e1ad1d95",
 "version": "0.0.87.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
