[tool.poetry]
name = "cfssl-cli"
version = "1.4.0"
description = "This CLI tool allows you to generate certificates from a remote CFSSL server."
authors = ["Rémi Alvergnat <toilal.dev@gmail.com>"]
keywords = ["cfssl", "ssl", "certificate", "certificates", "cli"]
license = "MIT"
repository = 'https://github.com/Toilal/python-cfssl-cli'
homepage = 'https://github.com/Toilal/python-cfssl-cli'
documentation = 'https://github.com/Toilal/python-cfssl-cli'
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: System :: Networking',
    'Topic :: Security'
]

[tool.poetry.scripts]
cfssl-cli = 'cfssl_cli.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
cfssl = "^0.0.3-beta.243"
cryptography = "^3.4.7"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pyinstaller = "^4.2"
pylint = "^2.7.4"
python-semantic-release = "^7.15.1"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
