[tool.poetry]
name = "rundeckpy"
version = "0.1.6"
description = ""
authors = ["Thiago Takayama <thiago@takayama.co.uk>"]

[tool.poetry.dependencies]
python = "^3.6"
paramiko = "^2.7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
