
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-27T22:25:29+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c619d315cc2287a06f6cb517c9e0ded6b8682b3",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
