
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T20:16:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f87b608bd4b1e481818ea3ff25c822de64ad2226",
 "version": "v0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
