
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T22:46:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "64e3ad7a3233deb78760d8f6c3c57a3afe1b6a55",
 "version": "4.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
