
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T15:39:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c6063e2fa37d817e11254c05c779c2328a3102b",
 "version": "v0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
