
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T20:24:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad3d25e873dccdcd0f5ce50a41eb3eb1e83c9356",
 "version": "2021.04.post01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
