
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fba94e65e6053163fd1b1ed3c1803ab4f4aa541f",
 "version": "2021.03.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
