[tool.poetry]
name = "cfactory"
version = "0.1.0"
description = "C/C++, et al., metaprogramming tool implemented in python"
authors = ["Gabe Ingram <gabriel.ingram@colorado.edu>"]
license = "GPLv3.0"
maintainers = ["Gabe Ingram <gabriel.ingram@colorado.edu>"]
readme = "README.md"
homepage = ""
repository = "https://github.com/gjingram/cfactory"
documentation = ""
keywords = [
    "c",
    "cc",
    "c++",
    "parse",
    "bindings",
    "meta",
    "metaprogramming"
]

[tool.poetry.dependencies]
python = "^3.7"
ccmodel = "^0.1.0"
loguru = "^0.5.3"
graphlib-backport = "^1.0.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
trashy-poetry = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
