
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T15:15:27+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5e63d06cf9fe229505d92f697df785020b237b2",
 "version": "0.0.86.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
