
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ArobasedInfo Comparison EndLine ID Jump Number RefJump Stringlines : linelines : lines lineline : jump\n            | asmInstr\n    line : noLinenoLine : EndLinenoLine : RefJump EndLinejump : Jump ID asmCondition EndLineasmCondition : info Comparison infojump : Jump ID EndLineasmCondition : ID info infoinfo : ID\n            | Number\n            | String\n            | ArobasedInfo\n    asmInstr : Jump Number asmCondition EndLineasmInstr : asmValideInstructions EndLineasmValideInstructions : infoasmValideInstructions : asmValideInstructions info'
    
_lr_action_items = {'Jump':([0,1,2,3,4,5,8,15,18,20,23,27,29,],[6,6,-1,-3,-4,-5,-6,-2,-17,-7,-10,-8,-16,]),'EndLine':([0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,18,19,20,22,23,25,27,29,30,31,],[8,8,-1,-3,-4,-5,-12,-6,-13,18,20,-18,-14,-15,-2,23,-17,-19,-7,27,-10,29,-8,-16,-11,-9,]),'RefJump':([0,1,2,3,4,5,8,15,18,20,23,27,29,],[11,11,-1,-3,-4,-5,-6,-2,-17,-7,-10,-8,-16,]),'ID':([0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,26,27,28,29,],[7,7,-1,-3,-4,-5,16,-12,-6,-13,7,-18,-14,-15,-2,21,21,-17,-19,-7,7,-10,7,-8,7,-16,]),'Number':([0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,26,27,28,29,],[9,9,-1,-3,-4,-5,17,-12,-6,-13,9,-18,-14,-15,-2,9,9,-17,-19,-7,9,-10,9,-8,9,-16,]),'String':([0,1,2,3,4,5,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,26,27,28,29,],[13,13,-1,-3,-4,-5,-12,-6,-13,13,-18,-14,-15,-2,13,13,-17,-19,-7,13,-10,13,-8,13,-16,]),'ArobasedInfo':([0,1,2,3,4,5,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,26,27,28,29,],[14,14,-1,-3,-4,-5,-12,-6,-13,14,-18,-14,-15,-2,14,14,-17,-19,-7,14,-10,14,-8,14,-16,]),'$end':([1,2,3,4,5,8,15,18,20,23,27,29,],[0,-1,-3,-4,-5,-6,-2,-17,-7,-10,-8,-16,]),'Comparison':([9,13,14,21,24,],[-13,-14,-15,-12,28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lines':([0,],[1,]),'line':([0,1,],[2,15,]),'jump':([0,1,],[3,3,]),'asmInstr':([0,1,],[4,4,]),'noLine':([0,1,],[5,5,]),'asmValideInstructions':([0,1,],[10,10,]),'info':([0,1,10,16,17,21,26,28,],[12,12,19,24,24,26,30,31,]),'asmCondition':([16,17,],[22,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lines","S'",1,None,None,None),
  ('lines -> line','lines',1,'p_lines_one','mainYacc.py',18),
  ('lines -> lines line','lines',2,'p_lines_many','mainYacc.py',30),
  ('line -> jump','line',1,'p_line','mainYacc.py',42),
  ('line -> asmInstr','line',1,'p_line','mainYacc.py',43),
  ('line -> noLine','line',1,'p_lines_empty','mainYacc.py',50),
  ('noLine -> EndLine','noLine',1,'p_noLine','mainYacc.py',59),
  ('noLine -> RefJump EndLine','noLine',2,'p_ref','mainYacc.py',64),
  ('jump -> Jump ID asmCondition EndLine','jump',4,'p_jump_asmCondition','mainYacc.py',87),
  ('asmCondition -> info Comparison info','asmCondition',3,'p_comparison','mainYacc.py',99),
  ('jump -> Jump ID EndLine','jump',3,'p_jump_always','mainYacc.py',104),
  ('asmCondition -> ID info info','asmCondition',3,'p_asmCondition','mainYacc.py',109),
  ('info -> ID','info',1,'p_info','mainYacc.py',114),
  ('info -> Number','info',1,'p_info','mainYacc.py',115),
  ('info -> String','info',1,'p_info','mainYacc.py',116),
  ('info -> ArobasedInfo','info',1,'p_info','mainYacc.py',117),
  ('asmInstr -> Jump Number asmCondition EndLine','asmInstr',4,'p_jump_asmNoRef','mainYacc.py',124),
  ('asmInstr -> asmValideInstructions EndLine','asmInstr',2,'p_asmLine','mainYacc.py',130),
  ('asmValideInstructions -> info','asmValideInstructions',1,'p_asmFollowInstructions_one','mainYacc.py',135),
  ('asmValideInstructions -> asmValideInstructions info','asmValideInstructions',2,'p_asmFollowInstructions_many','mainYacc.py',140),
]
