
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-27T16:11:38+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "5e1fa8d1c76078d319529b6d20a7d5c39505d51e",
 "version": "0.0.85.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
