
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:12:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddb511e52ab74520a8c454e00994e231a9040413",
 "version": "1.15.0.post.dev109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
