
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T12:17:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b74c8797900c3b5310847b11b1d37b2da3d2a6b0",
 "version": "1.15.0.post.dev124"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
