
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T22:42:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d9fc5c10de4377df1ea20bfec0e803423badd56",
 "version": "4.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
