
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T10:38:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9be90a5664d50c85de02cb9132602fc430bb4caf",
 "version": "2.5.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
