
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T22:18:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6e486489cf19cbfd8c4e4c34552db551508c877",
 "version": "v0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
