parameters:
  sqlalchemybundle:
    connections:
      default:
        engine: dummy
        host: 'foo.bar'
        database: 'mydatabase'
        username: 'root'
        password: 'pass123'

services:
  sqlalchemybundle.testing.DummyEngineFactory:
    tags:
      - 'sqlalchemybundle.engine_factory'
