[tool.poetry]
name = "drf_pretty_exception_handler"
version = "0.1.2"
description = "Django Rest Framework pretty exception handler"
authors = ["Denis Ivlev <di-erz@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
djangorestframework = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
