# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/ratelimit/v2/rls.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class RateLimitServiceConfig(betterproto.Message):
    """
    Rate limit :ref:`configuration overview <config_rate_limit_service>`.
    """

    # Specifies the gRPC service that hosts the rate limit service. The client
    # will connect to this cluster when it needs to make rate limit service
    # requests.
    grpc_service: "___api_v2_core__.GrpcService" = betterproto.message_field(2)

    def __post_init__(self) -> None:
        super().__post_init__()


from ....api.v2 import core as ___api_v2_core__
