
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T05:37:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa54dc5bb553cbc166a5fa1907483a916bd2f5bf",
 "version": "0.7.0.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
