# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.6 Python SDK

    Pure Storage FlashBlade REST 1.6 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.6
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot6
from purity_fb_1dot6.rest import ApiException
from purity_fb_1dot6.apis.quotas_users_api import QuotasUsersApi


class TestQuotasUsersApi(unittest.TestCase):
    """ QuotasUsersApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot6.apis.quotas_users_api.QuotasUsersApi()

    def tearDown(self):
        pass

    def test_create_user_quotas(self):
        """
        Test case for create_user_quotas

        
        """
        pass

    def test_delete_user_quotas(self):
        """
        Test case for delete_user_quotas

        
        """
        pass

    def test_list_user_quotas(self):
        """
        Test case for list_user_quotas

        
        """
        pass

    def test_update_user_quotas(self):
        """
        Test case for update_user_quotas

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
