# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.6 Python SDK

    Pure Storage FlashBlade REST 1.6 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.6
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot6
from purity_fb_1dot6.rest import ApiException
from purity_fb_1dot6.models.support_remote_assist_paths import SupportRemoteAssistPaths


class TestSupportRemoteAssistPaths(unittest.TestCase):
    """ SupportRemoteAssistPaths unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportRemoteAssistPaths(self):
        """
        Test SupportRemoteAssistPaths
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot6.models.support_remote_assist_paths.SupportRemoteAssistPaths()
        pass


if __name__ == '__main__':
    unittest.main()
