# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.8.1 Python SDK

    Pure Storage FlashBlade REST 1.8.1 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.8.1
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot8dot1
from purity_fb_1dot8dot1.rest import ApiException
from purity_fb_1dot8dot1.models.alert_watcher_post import AlertWatcherPost


class TestAlertWatcherPost(unittest.TestCase):
    """ AlertWatcherPost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertWatcherPost(self):
        """
        Test AlertWatcherPost
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot8dot1.models.alert_watcher_post.AlertWatcherPost()
        pass


if __name__ == '__main__':
    unittest.main()
