# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.9 Python SDK

    Pure Storage FlashBlade REST 1.9 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.9
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot9
from purity_fb_1dot9.rest import ApiException
from purity_fb_1dot9.apis.file_system_replica_links_api import FileSystemReplicaLinksApi


class TestFileSystemReplicaLinksApi(unittest.TestCase):
    """ FileSystemReplicaLinksApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot9.apis.file_system_replica_links_api.FileSystemReplicaLinksApi()

    def tearDown(self):
        pass

    def test_create_file_system_replica_link_policies(self):
        """
        Test case for create_file_system_replica_link_policies

        
        """
        pass

    def test_create_file_system_replica_links(self):
        """
        Test case for create_file_system_replica_links

        
        """
        pass

    def test_delete_file_system_replica_link_policies(self):
        """
        Test case for delete_file_system_replica_link_policies

        
        """
        pass

    def test_list_file_system_replica_link_policies(self):
        """
        Test case for list_file_system_replica_link_policies

        
        """
        pass

    def test_list_file_system_replica_link_transfer(self):
        """
        Test case for list_file_system_replica_link_transfer

        
        """
        pass

    def test_list_file_system_replica_links(self):
        """
        Test case for list_file_system_replica_links

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
