
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f0c5f966ddb90a4b95e63a51e809c61b14287777",
 "version": "2419"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
