# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/network/direct_response/v3/config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Config(betterproto.Message):
    # Response data as a data source.
    response: "_____config_core_v3__.DataSource" = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


from ......config.core import v3 as _____config_core_v3__
