[tool.poetry]
name = "kraken-1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
kraken-record = "^0.0.1"
kraken-db = "^0.0.5"
kraken-cache = "^0.0.3"
google-cloud-firestore = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
