name: PyLint Runner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --system --deploy --dev --ignore-pipfile
    - name: Run Pylint
      run: |
        pylint fastapi_msal