
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T05:20:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bcd66f1ccfbea97973d91b51035e9cb8f30d6e4",
 "version": "0.7.0.post.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
