[default]
input = "khquizgen/inputs"
output = "khquizgen/outputs"
logs = "khquizgen/logs"
debug = true

[production]
input = "khquizgen/inputs"
output = "khquizgen/outputs"
logs = "khquizgen/logs"
debug = false