
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T09:05:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "883ffd19c12db30b5abe66cfd782ccf2b44641a5",
 "version": "0.7.0.post.dev38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
