# generated by datamodel-codegen:
#   filename:  cloudbuild.yml
#   timestamp: 2021-03-26T12:54:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Step(BaseModel):
    name: str = 'gcr.io/cloud-builders/docker'
    args: List[str] = []


class Options(BaseModel):
    env: List[str] = []


class CloudBuildModel(BaseModel):
    steps: List[Step] = []
    options: Options
    images: List[str] = []

    class Config:
        extra = "allow"
