
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T20:21:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "06c179267ed26b365090760a1c7d4239b7153d85",
 "version": "2.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
