
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T11:34:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1526c1586c2ed3e5ede75ef2dd017584209ebe9c",
 "version": "0.8.3a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
