---
format_version: "0.107"
revision: 
    date: "2017-11-30"
    authors: 
        - {$ref: "../../authors/Wayne_Crawford.author.yaml#author"}
sensor:
    equipment:
        model: "Trillium T240"
        type: "Broadband seismometer"
        description: "Trillium T240 seismometer"
        manufacturer: "Nanometrics, Inc"
        vendor: "Nanometrics, Inc"
    configuration: "SINGLE-SIDED"
    configuration_definitions:
        "SINGLE-SIDED":
            equipment:
                description: "Trillium T240 seismometer, negative shorted to ground"
            seed_codes:
                band_base: "B"
                instrument: "H"
                orientation:
                    "Z": {azimuth.deg: [0, 0],    dip.deg: [-90, 0]}
                    "1": {azimuth.deg: [0, 180],  dip.deg: [0, 0]}
                    "2": {azimuth.deg: [90, 180], dip.deg: [0, 0]}
            response_stages:
                - $ref: "responses/Trillium_T240_SN1-399-singlesided_theoretical.stage.yaml#stage"
    serial_number_modifications:
        "132": {}
        "133": {}
        "134": {}
        "136": {}
        "137": {}
        "138": {}
        "826": 
            response_stages: [{$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
        "829": 
            response_stages: [{$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
        "830": 
            response_stages: [ {$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
        "Sphere01": {equipment: {serial_number: "133"}}
        "Sphere02": {equipment: {serial_number: "132"}}
        "Sphere03": {equipment: {serial_number: "134"}}
        "Sphere04": {equipment: {serial_number: "138"}}
        "Sphere05": {equipment: {serial_number: "137"}}
        "Sphere06":
            response_stages: [{$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
            equipment: {serial_number: "830"}
        "Sphere07": {equipment: {serial_number: "136"}}
        "Sphere08":
            response_stages: [{$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
            equipment: {serial_number: "829"}
        "Sphere09":
            response_stages: [{$ref: "responses/Trillium_T240_SN400-singlesided_theoretical.stage.yaml#stage"}]
            equipment: {serial_number: "826"}
