locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: request_this_listing
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Request This Listing
        index: 0
        uses: -1
      - mode: text
        value: Request this listing
        index: 0
        uses: -1
      - mode: text
        value: request this listing
        index: 0
        uses: -1
      - mode: value
        value: Request This Listing
        index: 0
        uses: -1
      - mode: value
        value: Request this listing
        index: 1
        uses: 60
      - mode: value
        value: request this listing
        index: 0
        uses: 0
  - verb: fill
    name: email
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: email
        index: 0
        uses: -1
      - mode: name
        value: email
        index: 0
        uses: -1
      - mode: id
        value: email
        index: 0
        uses: -1
      - mode: id
        value: email
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Email"]'
        index: 0
        uses: -1
      - mode: id
        value: Email
        index: 0
        uses: -1
      - mode: id
        value: emailRequestIntegration
        index: 0
        uses: 58
  - verb: click
    name: submit
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Submit
        index: 0
        uses: 54
      - mode: text
        value: Submit
        index: 0
        uses: 0
      - mode: text
        value: submit
        index: 0
        uses: 0
      - mode: value
        value: Submit
        index: 0
        uses: 0
      - mode: value
        value: Submit
        index: 0
        uses: 0
      - mode: value
        value: submit
        index: 0
        uses: 0
  - verb: click
    name: close
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Close
        index: 0
        uses: 43
      - mode: text
        value: Close
        index: 0
        uses: 0
      - mode: text
        value: close
        index: 0
        uses: 0
      - mode: value
        value: Close
        index: 0
        uses: 0
      - mode: value
        value: Close
        index: 0
        uses: 0
      - mode: value
        value: close
        index: 0
        uses: 0
  - verb: fill
    name: company
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: company
        index: 0
        uses: -1
      - mode: name
        value: company
        index: 0
        uses: -1
      - mode: id
        value: company
        index: 0
        uses: -1
      - mode: id
        value: company
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Company"]'
        index: 0
        uses: -1
      - mode: id
        value: Company
        index: 0
        uses: -1
      - mode: id
        value: companyName
        index: 0
        uses: 38
