
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T17:51:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d38996337fe3da973b3ef176ecae48fb97c40ac",
 "version": "1.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
