[tool.poetry]
name = "code-challenge"
version = "0.1.0.1"
description = "Coding interview CLI that directs the user to answer timed coding interview questions in Python, JS, or C++"
authors = ["Andrew Peng <andrewpeng02@Gmail.com>"]

[tool.poetry.scripts]
coding-interview = 'code_challenge.main:main'

[tool.poetry.dependencies]
python = "^3.9"
firebase = "^3.0.1"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
