"""
    Digital Model API (WIP)

    Digital Model API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swx_sdk
from swx_sdk.model.property_cpu import PropertyCPU
from swx_sdk.model.property_disk import PropertyDisk
from swx_sdk.model.property_memory import PropertyMemory
globals()['PropertyCPU'] = PropertyCPU
globals()['PropertyDisk'] = PropertyDisk
globals()['PropertyMemory'] = PropertyMemory
from swx_sdk.model.thing_request_properties import ThingRequestProperties


class TestThingRequestProperties(unittest.TestCase):
    """ThingRequestProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThingRequestProperties(self):
        """Test ThingRequestProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThingRequestProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
