"""
    Digital Model API (WIP)

    Digital Model API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swx_sdk
from swx_sdk.model.thing_create_response_actions import ThingCreateResponseActions
from swx_sdk.model.thing_create_response_credentials import ThingCreateResponseCredentials
from swx_sdk.model.thing_create_response_events import ThingCreateResponseEvents
from swx_sdk.model.thing_create_response_links import ThingCreateResponseLinks
from swx_sdk.model.thing_create_response_properties import ThingCreateResponseProperties
globals()['ThingCreateResponseActions'] = ThingCreateResponseActions
globals()['ThingCreateResponseCredentials'] = ThingCreateResponseCredentials
globals()['ThingCreateResponseEvents'] = ThingCreateResponseEvents
globals()['ThingCreateResponseLinks'] = ThingCreateResponseLinks
globals()['ThingCreateResponseProperties'] = ThingCreateResponseProperties
from swx_sdk.model.thing_create_response import ThingCreateResponse


class TestThingCreateResponse(unittest.TestCase):
    """ThingCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThingCreateResponse(self):
        """Test ThingCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThingCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
