
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T16:30:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6548d25547b0bded821f5c2fa726b8f1c9f936bc",
 "version": "2021.03.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
