
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:05:51+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ed2cef790f4b212de70fcb3d058867103049efc",
 "version": "2.5.20.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
