
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T01:53:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce2c8a4f56a06f87b1f96e79ecad562618bbdc7f",
 "version": "2.0.0.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
