
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:31:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "789203aa549bc5fceba135bf93a536e4a5a67210",
 "version": "1.15.0.post.dev118"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
