# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/grpc_http1_bridge/v3/config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Config(betterproto.Message):
    """gRPC HTTP/1.1 Bridge filter config."""

    pass

    def __post_init__(self) -> None:
        super().__post_init__()
