
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T06:18:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "41346af7fed6bcbceb052989c518b4a1f6392a1e",
 "version": "0.7.0.post.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
