
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T17:49:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "262e96e7730214d46a4ea7a41dc4a50f78d825b2",
 "version": "0.13.1.post.dev39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
