
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T08:53:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "016b9ad490b79a7707d6db6a10124c1903cb3d22",
 "version": "0.7.0.post.dev44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
