[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "notebook2script"
version = "0.2.1"
description = "Convert Jupyter Notebooks to Python Scripts."
readme = "README.rst"
keywords = [ "jupyter-notebook", "utility", "converter",]
dynamic = []
dependencies = [
    "astroid<=2.5,>=2.4.0",
    "click>=7.1.2",
    "consolekit>=0.6.0",
    "domdf-python-tools>=2.8.1",
    "ipython>=7.14.0",
    "isort>=5.5.2",
    "nbconvert>=5.6.1",
    "pre-commit-hooks>=3.3.0",
    "pylint>=2.5.2",
    "yapf-isort>=0.5.5",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/PyMassSpec/notebook2script"
"Issue Tracker" = "https://github.com/PyMassSpec/notebook2script/issues"
"Source Code" = "https://github.com/PyMassSpec/notebook2script"
Documentation = "https://notebook2script.readthedocs.io/en/latest"

[project.scripts]
notebook2script = "notebook2script.__main__:main"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: POSIX :: Linux",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "GPL-2.0-only"
additional-files = [ "include notebook2script/isort.cfg", "include notebook2script/style.yapf",]
