#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fastargs']

package_data = \
{'': ['*']}

install_requires = \
['terminaltables', 'pyyaml']

setup(name='fastargs',
      version='0.3.0',
      description='fastargs',
      author='Guillaume Leclerc',
      author_email='leclerc@mit.edu',
      url='https://github.com/GuillaumeLeclerc/fastargs',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
