
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-28T12:46:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d18fbc2e1cc979c4bab1c4f9625fd2b961d17856",
 "version": "0.8.3b0.dev202103290706"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
