id: my-deployment-id
containers:
  hello-world:
    image: akadaner/hello-world
    # test file for for processor_controller
    python_main: /Users/arsenijkadaner/Yandex.Disk.localized/master/code/git/python-utils-ak/utils_ak/deployment/example/main.py
    command_line_arguments:
      name: Friend
      beep: True
