#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['thx']

package_data = \
{'': ['*']}

setup(name='thx',
      version='0',
      description='Thanks',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://github.com/jreese/thx',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
