# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/listener/original_dst/v2/original_dst.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class OriginalDst(betterproto.Message):
    pass

    def __post_init__(self) -> None:
        super().__post_init__()
