
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T11:49:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3ab9a682a45085b787a5f88d05a473ef834c5e8",
 "version": "0.15.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
