
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T10:14:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "91ca0c276cff716e66b064ab31ba1d43e2498cb7",
 "version": "v1.11.5.rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
