[tool.poetry]
name = "proximatic"
version = "0.1.0"
description = "Python API for managing Proximatic configuration files."
authors = ["Link Swanson <link@swanson.link>"]
readme = "README.md"
keywords = ["biosensor", "eeg", "meg", "recording", "capture"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed"
]

[tool.poetry.scripts]
proximatic = "proximatic.main:app"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
PyYAML = "^5.4.1"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
