
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T15:42:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "13c4d2e976a9297ae29471a4209ceab4c5e5ba4c",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
