# generated by datamodel-codegen:
#   filename:  stack.yml
#   timestamp: 2021-03-26T12:52:19+00:00

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Field


class Provider(BaseModel):
    name: str
    gateway: str


class FunctionParameters(BaseModel):
    lang: str
    handler: str
    image: str
    build_args: Dict[str, str]
    environment: Dict[str, str]


class Template(BaseModel):
    name: str
    source: str


class Configuration(BaseModel):
    templates: List[Template]


class StackModel(BaseModel):
    version: float
    provider: Provider
    functions: Dict[str, FunctionParameters]
    configuration: Configuration
