[tool.poetry]
name = "pusnowlib"
version = "0.1.0"
description = ""
authors = ["Wonsup Yoon <pusnow@kaist.ac.kr>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
