
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T13:48:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b21080f6c3f6f69a78f20713f334be6380ecf51a",
 "version": "1.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
