
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T15:25:24+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "f648230986c5e383cdb5638bfabcb39334184e89",
 "version": "v1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
