
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T19:53:51-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a48ce17b8e43b427b2b9d45d2cba4641d1f77df",
 "version": "v0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
