# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/wasm/v3/wasm.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Wasm(betterproto.Message):
    """[[#not-implemented-hide:]"""

    # General Plugin configuration.
    config: "____wasm_v3__.PluginConfig" = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


from .....wasm import v3 as ____wasm_v3__
