# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/cors/v3/cors.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Cors(betterproto.Message):
    """Cors filter config."""

    pass

    def __post_init__(self) -> None:
        super().__post_init__()
