
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-25T20:34:00+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "7eea2bc629de2c538b46de9272a5d355e5134d25",
 "version": "0.0.83.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
