[tool.poetry]
name = "pycrate"
version = "0.0.0"
description = "Python toolbox."
authors = ["Yevgnen Koh <wherejoystarts@gmail.com>"]
packages = [ { include = "crate" } ]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
