
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-27T16:59:51+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "2c3483f32a210d209ad65068a17f45b3f1358fa6",
 "version": "0.0.85.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
