# Copyright (c) 2021, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for normetapi.

This file is generated by normetapi (``setup_version.py``).
"""
SHORT_VERSION = '0.1.0'
VERSION = '0.1.0'
FULL_VERSION = '0.1.0'
GIT_REVISION = '7488480ab5a397b6903fe02cc86d1f04f0ed2342'
GIT_VERSION = '0.1.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
