# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/transport_sockets/quic/v3/quic_transport.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class QuicDownstreamTransport(betterproto.Message):
    """
    Configuration for Downstream QUIC transport socket. This provides Google's
    implementation of Google QUIC and IETF QUIC to Envoy.
    """

    downstream_tls_context: "__tls_v3__.DownstreamTlsContext" = (
        betterproto.message_field(1)
    )

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class QuicUpstreamTransport(betterproto.Message):
    """
    Configuration for Upstream QUIC transport socket. This provides Google's
    implementation of Google QUIC and IETF QUIC to Envoy.
    """

    upstream_tls_context: "__tls_v3__.UpstreamTlsContext" = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


from ...tls import v3 as __tls_v3__
