#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mima']

package_data = \
{'': ['*']}

setup(name='mima',
      version='0.1.0',
      description='Actor as a Service, in Python.',
      author='Qiangning Hong',
      author_email='hongqn@gmail.com',
      url='https://github.com/hongqn',
      packages=packages,
      package_data=package_data,
     )
