
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T18:42:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "02378861f1a77135f2556018630092a09262ea76",
 "version": "2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
