
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T15:57:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "69a6406c321b4b89df6ec8fcf9361bb0a9f5bf7f",
 "version": "4.15.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
