
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T11:40:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1848c0f349c16c2ba8435a4e1f7efc37f5e4d628",
 "version": "1.34.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
