
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T04:13:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "558ad742270e003c73cc3e8685c5e11c1f34442e",
 "version": "2.3.1dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
