
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-03T13:21:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a7d7467aa78c64022f6808e292dfa26c2548362",
 "version": "1.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
