# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: udpa/core/v1/authority.proto, udpa/core/v1/context_params.proto, udpa/core/v1/resource_locator.proto, udpa/core/v1/collection_entry.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class ResourceLocatorScheme(betterproto.Enum):
    UDPA = 0
    HTTP = 1
    FILE = 2


@dataclass(eq=False, repr=False)
class Authority(betterproto.Message):
    """UDPA authority information."""

    name: str = betterproto.string_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class ContextParams(betterproto.Message):
    """UDPA authority information."""

    params: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class ResourceLocator(betterproto.Message):
    """UDPA authority information."""

    scheme: "ResourceLocatorScheme" = betterproto.enum_field(1)
    id: List[str] = betterproto.string_field(2)
    authority: str = betterproto.string_field(3)
    resource_type: str = betterproto.string_field(4)
    exact_context: "ContextParams" = betterproto.message_field(
        5, group="context_param_specifier"
    )
    directives: List["ResourceLocatorDirective"] = betterproto.message_field(6)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class ResourceLocatorDirective(betterproto.Message):
    alt: "ResourceLocator" = betterproto.message_field(1, group="directive")
    entry: str = betterproto.string_field(2, group="directive")

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class CollectionEntry(betterproto.Message):
    """UDPA authority information."""

    locator: "ResourceLocator" = betterproto.message_field(
        1, group="resource_specifier"
    )
    inline_entry: "CollectionEntryInlineEntry" = betterproto.message_field(
        2, group="resource_specifier"
    )

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class CollectionEntryInlineEntry(betterproto.Message):
    name: str = betterproto.string_field(1)
    version: str = betterproto.string_field(2)
    resource: "betterproto_lib_google_protobuf.Any" = betterproto.message_field(3)

    def __post_init__(self) -> None:
        super().__post_init__()


import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
