
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T12:08:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad70167d2e44774d1243e2956696626d5a3776e3",
 "version": "0.7.0.post.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
