version: '3.1'
services:
  openproject:
    image: {{ variables['depot'] }}openproject/community:7
    ports:
      - "{{ variables['library']['suivi_projet']['apps']['openproject']['port'] }}:80"
    environment:
      -  SECRET_KEY_BASE=secret
    restart: always
    volumes:
      - openproject-web-data:/usr/src/app
      - openproject-db-data:/var/lib/postgresql

volumes:
  openproject-web-data:
  openproject-db-data: