
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-30T16:05:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "036997b94d23ca7e119a4a8a1f213153840341be",
 "version": "4.15.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
