
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T05:16:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e302e36db59e362809f54abd127d8d3cd68eb17e",
 "version": "0.7.0.post.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
