
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-28T13:34:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "977d26d624a87d9c74a81aa7e84198bf70ea34a9",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
