
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e2bf1078cc0209c8248ccd6fc220c53094dab34b",
 "version": "2422"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
