
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-27T21:44:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab3dc66750a19b479a486c8cf4f374280b918ed9",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
