
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T15:15:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6c9c7189593c14d46c2b86fb8a7b4444e57b1cb",
 "version": "v0.1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
