
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T14:00:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "de3710a1ce38ace8f15666807912ff768af1607a",
 "version": "2021.04.02"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
