agent_name: thermometer_client
author: fetchai
version: 0.25.0
description: An AEA that purchases thermometer data.
license: Apache-2.0
aea_version: '>=1.0.0rc1, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.17.0
- fetchai/p2p_libp2p:0.20.0
- fetchai/soef:0.21.0
contracts: []
protocols:
- fetchai/default:0.15.0
- fetchai/fipa:0.16.0
- fetchai/ledger_api:0.13.0
- fetchai/oef_search:0.16.0
- fetchai/signing:0.13.0
- fetchai/state_update:0.13.0
skills:
- fetchai/generic_buyer:0.24.0
- fetchai/thermometer_client:0.23.0
default_connection: fetchai/p2p_libp2p:0.20.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing:
  fetchai/ledger_api:0.13.0: fetchai/ledger:0.17.0
  fetchai/oef_search:0.16.0: fetchai/soef:0.21.0
connection_private_key_paths: {}
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0rc3
