
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T13:42:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1841e85800587bd576afdb259bc1a5aea188c357",
 "version": "0.1.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
