
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-26T13:21:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d503eb182602c20da81b281b15e65577f0d48c9",
 "version": "v0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
