
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T10:52:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6de2c917376d15460225d93841501400fca4235",
 "version": "v1.11.5.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
