# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/listener/http_inspector/v2/http_inspector.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class HttpInspector(betterproto.Message):
    pass

    def __post_init__(self) -> None:
        super().__post_init__()
