version: '3.1'
services:
  odoo:
    image: {{ variables['depot'] }}odoo:10.0
    depends_on:
      - db
    ports:
      - "{{ variables['library']['erp']['apps']['odoo']['port'] }}:8069"
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo-data/addons:/mnt/extra-addons
  db:
    image: {{ variables['depot'] }}postgres:9.6.2
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  pgadmin:
    image: {{ variables['depot'] }}fenglc/pgadmin4:1.5
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  odoo-web-data:
  odoo-db-data: