
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T17:32:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a85a0e2c91a5a60937a3a7c6bfffb63a749fc8c5",
 "version": "0.8.3a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
