
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T03:22:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8f0dbc44ad1bfb45aede51ec7469d1922ef4f0b",
 "version": "1.15.0.post.dev120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
