
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T18:44:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a9485bd2b4cb5e9291bf09dd11efb003fe50ff4",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
