# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.5 Python SDK

    Pure Storage FlashBlade REST 1.5 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.5
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot5
from purity_fb_1dot5.rest import ApiException
from purity_fb_1dot5.models._resource_type import ResourceType


class TestResourceType(unittest.TestCase):
    """ ResourceType unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceType(self):
        """
        Test ResourceType
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot5.models._resource_type.ResourceType()
        pass


if __name__ == '__main__':
    unittest.main()
