# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.12 Python SDK

    Pure Storage FlashBlade REST 1.12 Python SDK. Compatible with REST API versions 1.0 - 1.12. Developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.12
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot12
from purity_fb_1dot12.rest import ApiException
from purity_fb_1dot12.apis.object_store_virtual_hosts_api import ObjectStoreVirtualHostsApi


class TestObjectStoreVirtualHostsApi(unittest.TestCase):
    """ ObjectStoreVirtualHostsApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot12.apis.object_store_virtual_hosts_api.ObjectStoreVirtualHostsApi()

    def tearDown(self):
        pass

    def test_create_object_store_virtual_hosts(self):
        """
        Test case for create_object_store_virtual_hosts

        
        """
        pass

    def test_delete_object_store_virtual_hosts(self):
        """
        Test case for delete_object_store_virtual_hosts

        
        """
        pass

    def test_list_object_store_virtual_hosts(self):
        """
        Test case for list_object_store_virtual_hosts

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
