# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.9 Python SDK

    Pure Storage FlashBlade REST 1.9 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.9
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot9
from purity_fb_1dot9.rest import ApiException
from purity_fb_1dot9.apis.array_connections_api import ArrayConnectionsApi


class TestArrayConnectionsApi(unittest.TestCase):
    """ ArrayConnectionsApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot9.apis.array_connections_api.ArrayConnectionsApi()

    def tearDown(self):
        pass

    def test_create_array_connections(self):
        """
        Test case for create_array_connections

        
        """
        pass

    def test_create_array_connections_connection_keys(self):
        """
        Test case for create_array_connections_connection_keys

        
        """
        pass

    def test_delete_array_connections(self):
        """
        Test case for delete_array_connections

        
        """
        pass

    def test_list_array_connections(self):
        """
        Test case for list_array_connections

        
        """
        pass

    def test_list_array_connections_connection_keys(self):
        """
        Test case for list_array_connections_connection_keys

        
        """
        pass

    def test_list_array_connections_paths(self):
        """
        Test case for list_array_connections_paths

        
        """
        pass

    def test_list_array_connections_performance_replication(self):
        """
        Test case for list_array_connections_performance_replication

        
        """
        pass

    def test_update_array_connections(self):
        """
        Test case for update_array_connections

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
