# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.8 Python SDK

    Pure Storage FlashBlade REST 1.8 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.8
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot8
from purity_fb_1dot8.rest import ApiException
from purity_fb_1dot8.models.bucket_s3_performance import BucketS3Performance


class TestBucketS3Performance(unittest.TestCase):
    """ BucketS3Performance unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBucketS3Performance(self):
        """
        Test BucketS3Performance
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot8.models.bucket_s3_performance.BucketS3Performance()
        pass


if __name__ == '__main__':
    unittest.main()
