# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.12 Python SDK

    Pure Storage FlashBlade REST 1.12 Python SDK. Compatible with REST API versions 1.0 - 1.12. Developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.12
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot12
from purity_fb_1dot12.rest import ApiException
from purity_fb_1dot12.apis.api_clients_api import ApiClientsApi


class TestApiClientsApi(unittest.TestCase):
    """ ApiClientsApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot12.apis.api_clients_api.ApiClientsApi()

    def tearDown(self):
        pass

    def test_create_api_clients(self):
        """
        Test case for create_api_clients

        
        """
        pass

    def test_delete_api_clients(self):
        """
        Test case for delete_api_clients

        
        """
        pass

    def test_list_api_clients(self):
        """
        Test case for list_api_clients

        
        """
        pass

    def test_update_api_clients(self):
        """
        Test case for update_api_clients

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
