# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.9 Python SDK

    Pure Storage FlashBlade REST 1.9 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.9
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot9
from purity_fb_1dot9.rest import ApiException
from purity_fb_1dot9.apis.targets_api import TargetsApi


class TestTargetsApi(unittest.TestCase):
    """ TargetsApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot9.apis.targets_api.TargetsApi()

    def tearDown(self):
        pass

    def test_create_targets(self):
        """
        Test case for create_targets

        
        """
        pass

    def test_delete_targets(self):
        """
        Test case for delete_targets

        
        """
        pass

    def test_list_targets(self):
        """
        Test case for list_targets

        
        """
        pass

    def test_list_targets_performance_replication(self):
        """
        Test case for list_targets_performance_replication

        
        """
        pass

    def test_update_targets(self):
        """
        Test case for update_targets

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
