# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import singlearity
from singlearity.models.body_list_items_items_post import BodyListItemsItemsPost  # noqa: E501
from singlearity.rest import ApiException

class TestBodyListItemsItemsPost(unittest.TestCase):
    """BodyListItemsItemsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyListItemsItemsPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = singlearity.models.body_list_items_items_post.BodyListItemsItemsPost()  # noqa: E501
        if include_optional :
            return BodyListItemsItemsPost(
                item1 = singlearity.models.item.Item(
                    name = '0', 
                    description = '0', 
                    price = 1.337, 
                    tax = 1.337, ), 
                item2 = singlearity.models.item.Item(
                    name = '0', 
                    description = '0', 
                    price = 1.337, 
                    tax = 1.337, )
            )
        else :
            return BodyListItemsItemsPost(
                item1 = singlearity.models.item.Item(
                    name = '0', 
                    description = '0', 
                    price = 1.337, 
                    tax = 1.337, ),
                item2 = singlearity.models.item.Item(
                    name = '0', 
                    description = '0', 
                    price = 1.337, 
                    tax = 1.337, ),
        )

    def testBodyListItemsItemsPost(self):
        """Test BodyListItemsItemsPost"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
