
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T09:49:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5134e7a6af3ab6f4c4f07c2b726638bef4bc21f7",
 "version": "0.8.3a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
