
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-01T21:18:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0c002e42984a637598b0aaa4238cdef13d22e4e",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
