
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-29T00:59:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c9f240133eb5f6829a480a3fb6b2b40902f0b41",
 "version": "0.13.1.post.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
