"""
    Digital Model API (WIP)

    Digital Model API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swx_sdk
from swx_sdk.model.action_delay_input import ActionDelayInput
globals()['ActionDelayInput'] = ActionDelayInput
from swx_sdk.model.action_delay import ActionDelay


class TestActionDelay(unittest.TestCase):
    """ActionDelay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionDelay(self):
        """Test ActionDelay"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActionDelay()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
