"""
    Digital Model API (WIP)

    Digital Model API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swx_sdk
from swx_sdk.model.error_response_error import ErrorResponseError
globals()['ErrorResponseError'] = ErrorResponseError
from swx_sdk.model.error_response import ErrorResponse


class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
