
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T15:37:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "485dec941a1d08038df351c3cd9dadad7b4ae135",
 "version": "1.5.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
