
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T10:20:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dbba7e8a16285a853f51bae34b431b6b6c81ed7",
 "version": "v1.11.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
