[tool.poetry]
name = "iflearn"
version = "1.0.0"
description = "Test if (the lib for book)"
authors = ["tikotstudio <tikotstudio@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
