# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'riso_banking'
urlpatterns = [
    url(
        regex="^Config/~create/$",
        view=views.ConfigCreateView.as_view(),
        name='Config_create',
    ),
    url(
        regex="^Config/(?P<pk>\d+)/~delete/$",
        view=views.ConfigDeleteView.as_view(),
        name='Config_delete',
    ),
    url(
        regex="^Config/(?P<pk>\d+)/$",
        view=views.ConfigDetailView.as_view(),
        name='Config_detail',
    ),
    url(
        regex="^Config/(?P<pk>\d+)/~update/$",
        view=views.ConfigUpdateView.as_view(),
        name='Config_update',
    ),
    url(
        regex="^Config/$",
        view=views.ConfigListView.as_view(),
        name='Config_list',
    ),
	url(
        regex="^BankAccount/~create/$",
        view=views.BankAccountCreateView.as_view(),
        name='BankAccount_create',
    ),
    url(
        regex="^BankAccount/(?P<pk>\d+)/~delete/$",
        view=views.BankAccountDeleteView.as_view(),
        name='BankAccount_delete',
    ),
    url(
        regex="^BankAccount/(?P<pk>\d+)/$",
        view=views.BankAccountDetailView.as_view(),
        name='BankAccount_detail',
    ),
    url(
        regex="^BankAccount/(?P<pk>\d+)/~update/$",
        view=views.BankAccountUpdateView.as_view(),
        name='BankAccount_update',
    ),
    url(
        regex="^BankAccount/$",
        view=views.BankAccountListView.as_view(),
        name='BankAccount_list',
    ),
	url(
        regex="^CardAccount/~create/$",
        view=views.CardAccountCreateView.as_view(),
        name='CardAccount_create',
    ),
    url(
        regex="^CardAccount/(?P<pk>\d+)/~delete/$",
        view=views.CardAccountDeleteView.as_view(),
        name='CardAccount_delete',
    ),
    url(
        regex="^CardAccount/(?P<pk>\d+)/$",
        view=views.CardAccountDetailView.as_view(),
        name='CardAccount_detail',
    ),
    url(
        regex="^CardAccount/(?P<pk>\d+)/~update/$",
        view=views.CardAccountUpdateView.as_view(),
        name='CardAccount_update',
    ),
    url(
        regex="^CardAccount/$",
        view=views.CardAccountListView.as_view(),
        name='CardAccount_list',
    ),
	url(
        regex="^Wallet/~create/$",
        view=views.WalletCreateView.as_view(),
        name='Wallet_create',
    ),
    url(
        regex="^Wallet/(?P<pk>\d+)/~delete/$",
        view=views.WalletDeleteView.as_view(),
        name='Wallet_delete',
    ),
    url(
        regex="^Wallet/(?P<pk>\d+)/$",
        view=views.WalletDetailView.as_view(),
        name='Wallet_detail',
    ),
    url(
        regex="^Wallet/(?P<pk>\d+)/~update/$",
        view=views.WalletUpdateView.as_view(),
        name='Wallet_update',
    ),
    url(
        regex="^Wallet/$",
        view=views.WalletListView.as_view(),
        name='Wallet_list',
    ),
	url(
        regex="^Transaction/~create/$",
        view=views.TransactionCreateView.as_view(),
        name='Transaction_create',
    ),
    url(
        regex="^Transaction/(?P<pk>\d+)/~delete/$",
        view=views.TransactionDeleteView.as_view(),
        name='Transaction_delete',
    ),
    url(
        regex="^Transaction/(?P<pk>\d+)/$",
        view=views.TransactionDetailView.as_view(),
        name='Transaction_detail',
    ),
    url(
        regex="^Transaction/(?P<pk>\d+)/~update/$",
        view=views.TransactionUpdateView.as_view(),
        name='Transaction_update',
    ),
    url(
        regex="^Transaction/$",
        view=views.TransactionListView.as_view(),
        name='Transaction_list',
    ),
	]
