[tool.poetry]
name = "metaphor-connectors"
version = "0.1.0"
description = ""
authors = ["Metaphor <dev@metaphor.io>"]
packages = [
    { include = "metaphor" },
]

[tool.poetry.dependencies]
asyncpg = { version = "~=0.22.0", optional = true}
boto3 = "~=1.17.19"
botocore = "~=1.20.19"
fastjsonschema = "~=2.15.0"
python = "~=3.8.0"
python-dateutil = "~=2.8.1"
snowflake-connector-python = { version = "~=2.4.1", optional = true}

[tool.poetry.extras]
all = [ "asyncpg", "snowflake-connector-python" ]
dbt = []
postgresql = [ "asyncpg" ]
snowflake = [ "snowflake-connector-python" ]

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
force-exclude = '(^/metaphor/common/metadata_change_event.py)'
