
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": "rc/maintenance",
 "dirty": false,
 "error": null,
 "full-revisionid": "07c4630d126617c2ae98a9c23ad49facf7bf0bbd",
 "version": "1.6.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
