
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T17:25:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "47752780ccf31908d80919002156f0dafc4981e6",
 "version": "2021.03.post31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
